name: daylog
description: Offline-first daily journal and time tracker
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # local db

  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.1

  # state management
  flutter_riverpod: ^2.4.9

  # notifications (offline, no internet needed)
  flutter_local_notifications: ^20.1.0
  timezone: ^0.10.1

  # utils
  share_plus: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  isar_generator: ^3.1.0
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/daylog_icon_1024.png"
  adaptive_icon_background: "#1D9E75"
  adaptive_icon_foreground: "assets/icon/daylog_icon_1024.png"
flutter:
  uses-material-design: true
